### ISSUE TITLE
Remove Jquery Dependency

### ISSUE THREAD

**Issue by Braden-Preston** [HarvestHaven/TPOT-Toolbox#19]
There is one function in the entire app that uses JQuery. I would like somebody to find the code for the $.parentUntil function in the JQuery library and write it out by hand as a function in the transforms.jsx or wherever the function makes sense. Then test the Editor to make certain there is no error in conversion or editing docs.

**Comment by nickpreston24** [comment]
I can do this tonight in addition to other things I'm working on.

**Comment by nickpreston24** [comment]
I've added a [branch](https://github.com/HarvestHaven/TPOT-Toolbox/tree/parents-until-implementation) with what looks like a suitable substitute for jQuery's parentsUntil().  There may be key differences, even though I get back what looks like the exact same element(s).  See todos.
