### ISSUE TITLE
Fix deployment issues with Netlify

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#20]
There are deployment scripts that are failing (e.g. 'headers') when trying to pass Netlify's checks.
https://github.com/HarvestHaven/TPOT-Toolbox/pull/18

**Comment by Braden-Preston** [comment]
We probably can't do anything with this right now until we clean the dependencies and crap classes by hand. I am closer to this now. I cleaned up the root store in a separate branch and I am using Scribe as the new model for what a clean store should be. Having the cleaner and predictable structure in places leaves me more comfortable to start removing thing lsnwe don't need. Getting there.

**Comment by Harvest-Haven-Apps** [comment]
Closing for now.
