### ISSUE TITLE
Development branch deployment for Netlify

### ISSUE THREAD

**Issue by Braden-Preston** [HarvestHaven/TPOT-Toolbox#23]
Right now we auto-deploy the Master branch directly to Netlify. You can see the contents of `master` on that domain

__Branch:__ `master` => [tpot.netlify.com](https:www.tpot.netlify.com)

I would like Netlify to do its auto-deployment not for just `master`, but the `development` branch as well, so that `development` has its own subdomain, in likeness to the following:

__Branch:__ `deployment` => [dev.tpot.netlify.com](https:www.dev.tpot.netlify.com)

Somebody should tackle this, but with the utmost care. I understand Netlify accepts .config files in the projects root directory to help with configuration, but we should talk about it if that's the case.

**Comment by Braden-Preston** [comment]
@MikePreston17, this is what we were talking about today.

**Comment by nickpreston24** [comment]
Yeah, will start on that tomorrow.  Should be pretty easy.

**Comment by Braden-Preston** [comment]
Netlify automatically is building URL's for our specified deploy branches, including `development`. Here is the URL:

https://development--tpot.netlify.com
