### ISSUE TITLE
Clear Button Doesn't Work

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#33]
Attempt to clear document in app in order to start new file failed as seen here https://s.nimbusweb.me/image/3235282/64sw5gm99bx845189hg6/oO7LS5cYYL1GS58u/gWNtOPtLXSIrifd2/ClearingDoesNotWork.gif

**Comment by Braden-Preston** [comment]
We have that fixed in our current build. Thanks for reminding us. :)

**Comment by AlanAgnew** [comment]
Sweet.
