### ISSUE TITLE
Preview Button on Publish Fails

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#37]
Preview button as seen in the below photo does not work.

https://s.nimbusweb.me/image/3235392/vo84xqoept73nmlbz19c/z84YeAJJEyyxLePz/j0fgLLNOsrLhAiyO/PreviewButtonFails.png

**Comment by Braden-Preston** [comment]
Placeholder for now. We will have a preview function at a later time, so that we can view what it will look like on the TPOT site before publishing. It requires a bit of difficult emulation, so it is a 'nice to have' for now.
