### ISSUE TITLE
Save Button Does Nothing

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#39]
The Save button on the left menu does not do anything.

**Comment by AlanAgnew** [comment]
@Braden-Preston and @MikePreston17, in this case, there isn't even a new log that pops up whenever I click on Save. No bug either. It's a dud. I mention this because this issue was brought up as an example by Michael. Even though it and other issues have had nothing interesting in the console, it seemed good to mention what happened with the Save issue due to what Michael said earlier.

**Comment by nickpreston24** [comment]
We are moving this button and potentially having an autosave feature which is in development.  The button may or may not return, but that's unlikely so I'm closing this one for now.
