### ISSUE TITLE
"Account" Option Non-Functional in Account Menu

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#42]
The option shown in [this photo](https://s.nimbusweb.me/image/3235404/h1uy7avz4wtygmtaybio/yeuD9UQDi4KCQaOg/8vn9tZ78EyxQgisb/BadAccountOption.png) does not work.

**Comment by Braden-Preston** [comment]
Account will live under the new settings page when it is done. See https://github.com/HarvestHaven/TPOT-Toolbox/issues/38#issuecomment-524691020
