### ISSUE TITLE
Details Option in Account Menu Does Not Work

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#43]
The [Details option shown here](https://s.nimbusweb.me/image/3235404/h1uy7avz4wtygmtaybio/yeuD9UQDi4KCQaOg/qSug7RxmD9z6ucVk/BadDetailsOption.png) does not work.

**Comment by Braden-Preston** [comment]
Details of a person's account will be under the new settings page when it is done. See https://github.com/HarvestHaven/TPOT-Toolbox/issues/38#issuecomment-524691020
