### ISSUE TITLE
Extra hangoff from line break

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#5]
Extra closing tag added to the end:

![2019-05-26 20_33_12-localhost_3000](https://user-images.githubusercontent.com/9275026/58390217-b44a6400-7ff5-11e9-87a2-a366cf247ff4.png)

**Comment by Braden-Preston** [comment]
Fixed in 9ad370186fb93f444bb8dd4a06cad23c5cdadc49. Culprit was Editor.jsx
