### ISSUE TITLE
Firebase Modal correction

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#8]

**Comment by Braden-Preston** [comment]
The firebase modal is in a class, ModalFirebase which **should** be called by the AuthButton class. The authButton class needs to be placed inside the app's header so we can click on it, open up the firebase modal and submit user credentials, account creation, etc.

**Comment by Braden-Preston** [comment]
@MikePreston17 Added back the AuthButton class among others in c17e9bcf393f6931f40dcce347b3566789ec3d5c. Many are not needed anymore but will be filtered out and removed in later versions as the UI matures and solidifies.

**Comment by nickpreston24** [comment]
Added the button to Header.jsx.  I goofed and disturbed the config on https://github.com/HarvestHaven/TPOT-Toolbox/issues/9.  Undid all that on my local and it's not complaining about a missing apikey.  Tldr: false alarm.
- [x] Still need to figure out if auth's functions (signin, signout, etc.) still work.  

**_Working on that tomorrow or any of the other Issues available._**

**Comment by nickpreston24** [comment]
They work.  Now to ensure auth works everywhere sessionStore goes.

**Comment by Braden-Preston** [comment]
As you can probably imagine: auth.jsx, auth.js and session.js will all get reorganized at some point. 

For the long term, I think there should be app-specific stores (where everything pertaining to that app is stuffed in) and there should be a toolbox store, which basically serves the role of auth and session together. I'd imagine given any store, there won't be more than a hundred observables and actions. Just one store per app, even if large is sufficient. 

Remember if we were using Redux, we would just have a single massive store with 400+ reducers in it. It just seems too heavy, and it doesn't give us the easy freedom of enabling or disabling apps, restarting one app, but not the other, loading up multiple sessions of Letters (future), etc.

**Comment by Braden-Preston** [comment]
ModalFirebase and AuthButton are back and working just fine after 78fbc622e9aec558f11131625909918ddca59134. Closing this issue for now.
