### ISSUE TITLE
Firebase Bad Authenticator

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#9]

**Comment by Braden-Preston** [comment]
Firebase is hooked up, but anybody can get the WP_Credentials from the Firestore. I don't think the function in the store is correctly checking for a non-null authUser state. That or firebase.firestore().auth isn't even initialized, which means there is no [*firebaseinstance*]onAuthState.() callback, which is responsible for setting authUser properly, allowing WP Creds to be pulled from the store without proper authentication. 

Isn't a problem now for the MVP roadmap, but super problematic later on. Anybody could post to TPOT and if a bad actor understands that we are using Firebase, they can store a reference to the instanced firebase object via the console and then call firebase functions that allow the deletion of posts en masse.

**Comment by Braden-Preston** [comment]
["Firebase is hooked up"]()

Turns out this isn't the case. We can't publish because there is no token and there is no token because there is no UI to sign in yet. I am adding in the AuthButton for somebody (anybody) to hook back up.

**Comment by nickpreston24** [comment]
Token is invalid.  Trying to figure out why this keeps happening over and over and why copying the given key (Console) doesn't seem to work.  Looking for a permanent solution and more understanding of firebase Auth as a whole so this issue doesn't repeat.  I've had it in other apps as well.

**Comment by nickpreston24** [comment]
The apiKey was coming back undefined as it was wrapped in Module > default {}.  Altered code so that the import was a const over a */default.

![image](https://user-images.githubusercontent.com/9275026/59546793-99368a00-8ef9-11e9-9e80-d6dd23b66b08.png)

![image](https://user-images.githubusercontent.com/9275026/59546767-20cfc900-8ef9-11e9-94da-c45ad70a22d9.png)

**Comment by Braden-Preston** [comment]
Firebase sign in hooked back up as of 78fbc622e9aec558f11131625909918ddca59134. Pulling WP credentials will not happen without authentication and publishing a paper will not work without the WP credentials either. Which is exactly what we need to happen.
